/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param success 
 * @param email 
 * @param message 
 * @param timestamp 
 */
@Serializable

data class AdminCreatedResponse (

    @SerialName(value = "success") @Required val success: kotlin.Boolean,

    @SerialName(value = "email") @Required val email: kotlin.String,

    @SerialName(value = "message") @Required val message: kotlin.String,

    @SerialName(value = "timestamp") @Required val timestamp: kotlin.Long

) {


}

