/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param iconUrl 
 * @param badgeType 
 * @param createdAt 
 * @param description 
 * @param criteria 
 */
@Serializable

data class Badge (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "iconUrl") @Required val iconUrl: kotlin.String,

    @SerialName(value = "badgeType") @Required val badgeType: Badge.BadgeType,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.String,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "criteria") val criteria: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: COURSE_COMPLETION,THEME_COMPLETION,STREAK,ACHIEVEMENT
     */
    @Serializable
    enum class BadgeType(val value: kotlin.String) {
        @SerialName(value = "COURSE_COMPLETION") COURSE_COMPLETION("COURSE_COMPLETION"),
        @SerialName(value = "THEME_COMPLETION") THEME_COMPLETION("THEME_COMPLETION"),
        @SerialName(value = "STREAK") STREAK("STREAK"),
        @SerialName(value = "ACHIEVEMENT") ACHIEVEMENT("ACHIEVEMENT");
    }

}

