/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param authorId 
 * @param language 
 * @param isPublished 
 * @param createdAt 
 * @param updatedAt 
 * @param posterId 
 * @param description 
 * @param authorUrl 
 */
@Serializable

data class Course (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "authorId") @Required val authorId: kotlin.String,

    @SerialName(value = "language") @Required val language: kotlin.String,

    @SerialName(value = "isPublished") @Required val isPublished: kotlin.Boolean,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.String,

    @SerialName(value = "updatedAt") @Required val updatedAt: kotlin.String,

    @SerialName(value = "posterId") val posterId: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "authorUrl") val authorUrl: kotlin.String? = null

) {


}

