/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.SectionProgressItem

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param courseId 
 * @param totalTasks 
 * @param completedTasks 
 * @param progressPercentage 
 * @param sectionsProgress 
 */
@Serializable

data class CourseProgressItem (

    @SerialName(value = "courseId") @Required val courseId: kotlin.String,

    @SerialName(value = "totalTasks") @Required val totalTasks: kotlin.Int,

    @SerialName(value = "completedTasks") @Required val completedTasks: kotlin.Int,

    @SerialName(value = "progressPercentage") @Required val progressPercentage: kotlin.String,

    @SerialName(value = "sectionsProgress") @Required val sectionsProgress: kotlin.collections.List<SectionProgressItem>

) {


}

