/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param themeId 
 * @param name 
 * @param taskType 
 * @param question 
 * @param isTraining 
 * @param orderNum 
 * @param instructions 
 */
@Serializable

data class CreateTaskRequest (

    @SerialName(value = "themeId") @Required val themeId: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "taskType") @Required val taskType: CreateTaskRequest.TaskType,

    @SerialName(value = "question") @Required val question: kotlin.String,

    @SerialName(value = "isTraining") @Required val isTraining: kotlin.Boolean,

    @SerialName(value = "orderNum") @Required val orderNum: kotlin.Int,

    @SerialName(value = "instructions") val instructions: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: LISTEN_AND_CHOOSE,READ_AND_CHOOSE,LOOK_AND_CHOOSE,MATCH_AUDIO_TEXT,MATCH_TEXT_TEXT
     */
    @Serializable
    enum class TaskType(val value: kotlin.String) {
        @SerialName(value = "LISTEN_AND_CHOOSE") LISTEN_AND_CHOOSE("LISTEN_AND_CHOOSE"),
        @SerialName(value = "READ_AND_CHOOSE") READ_AND_CHOOSE("READ_AND_CHOOSE"),
        @SerialName(value = "LOOK_AND_CHOOSE") LOOK_AND_CHOOSE("LOOK_AND_CHOOSE"),
        @SerialName(value = "MATCH_AUDIO_TEXT") MATCH_AUDIO_TEXT("MATCH_AUDIO_TEXT"),
        @SerialName(value = "MATCH_TEXT_TEXT") MATCH_TEXT_TEXT("MATCH_TEXT_TEXT");
    }

}

