/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param isCorrect 
 * @param orderNum 
 * @param optionText 
 * @param optionAudioId 
 */
@Serializable

data class CreateTaskAnswerOptionRequest (

    @SerialName(value = "isCorrect") @Required val isCorrect: kotlin.Boolean,

    @SerialName(value = "orderNum") @Required val orderNum: kotlin.Int,

    @SerialName(value = "optionText") val optionText: kotlin.String? = null,

    @SerialName(value = "optionAudioId") val optionAudioId: kotlin.String? = null

) {


}

