/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param success 
 * @param error 
 * @param timestamp 
 * @param code 
 */
@Serializable

data class ErrorResponse (

    @SerialName(value = "success") @Required val success: kotlin.Boolean,

    @SerialName(value = "error") @Required val error: kotlin.String,

    @SerialName(value = "timestamp") @Required val timestamp: kotlin.Long,

    @SerialName(value = "code") val code: kotlin.Int? = null

) {


}

