/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param studentsCount 
 * @param averageTimeSpentSeconds 
 * @param averageProgressPercentage 
 */
@Serializable

data class OverallCourseStatisticsResponse (

    @SerialName(value = "studentsCount") val studentsCount: kotlin.Long? = null,

    @SerialName(value = "averageTimeSpentSeconds") val averageTimeSpentSeconds: kotlin.Long? = null,

    @SerialName(value = "averageProgressPercentage") val averageProgressPercentage: kotlin.Double? = null

) {


}

