/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param courseId 
 * @param name 
 * @param orderNum 
 * @param createdAt 
 * @param description 
 */
@Serializable

data class Section (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "courseId") @Required val courseId: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "orderNum") @Required val orderNum: kotlin.Int,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.String,

    @SerialName(value = "description") val description: kotlin.String? = null

) {


}

