/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param answerType 
 * @param correctAnswer 
 */
@Serializable

data class UpdateTaskAnswerRequest (

    @SerialName(value = "answerType") val answerType: UpdateTaskAnswerRequest.AnswerType? = null,

    @SerialName(value = "correctAnswer") val correctAnswer: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: MULTIPLE_CHOICE_SHORT,MULTIPLE_CHOICE_LONG,SINGLE_CHOICE_SHORT,SINGLE_CHOICE_LONG,TEXT_INPUT,WORD_ORDER,WORD_SELECTION
     */
    @Serializable
    enum class AnswerType(val value: kotlin.String) {
        @SerialName(value = "MULTIPLE_CHOICE_SHORT") MULTIPLE_CHOICE_SHORT("MULTIPLE_CHOICE_SHORT"),
        @SerialName(value = "MULTIPLE_CHOICE_LONG") MULTIPLE_CHOICE_LONG("MULTIPLE_CHOICE_LONG"),
        @SerialName(value = "SINGLE_CHOICE_SHORT") SINGLE_CHOICE_SHORT("SINGLE_CHOICE_SHORT"),
        @SerialName(value = "SINGLE_CHOICE_LONG") SINGLE_CHOICE_LONG("SINGLE_CHOICE_LONG"),
        @SerialName(value = "TEXT_INPUT") TEXT_INPUT("TEXT_INPUT"),
        @SerialName(value = "WORD_ORDER") WORD_ORDER("WORD_ORDER"),
        @SerialName(value = "WORD_SELECTION") WORD_SELECTION("WORD_SELECTION");
    }

}

