/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param status 
 * @param attemptCount 
 * @param isCorrect 
 * @param shouldRetryAfterTasks 
 */
@Serializable

data class UpdateTaskProgressRequest (

    @SerialName(value = "status") val status: UpdateTaskProgressRequest.Status? = null,

    @SerialName(value = "attemptCount") val attemptCount: kotlin.Int? = null,

    @SerialName(value = "isCorrect") val isCorrect: kotlin.Boolean? = null,

    @SerialName(value = "shouldRetryAfterTasks") val shouldRetryAfterTasks: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: NOT_STARTED,IN_PROGRESS,COMPLETED,PENDING_RETRY
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "NOT_STARTED") NOT_STARTED("NOT_STARTED"),
        @SerialName(value = "IN_PROGRESS") IN_PROGRESS("IN_PROGRESS"),
        @SerialName(value = "COMPLETED") COMPLETED("COMPLETED"),
        @SerialName(value = "PENDING_RETRY") PENDING_RETRY("PENDING_RETRY");
    }

}

