/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param contentType 
 * @param contentId 
 * @param description 
 * @param transcription 
 * @param translation 
 * @param orderNum 
 */
@Serializable

data class UpdateTaskContentRequest (

    @SerialName(value = "contentType") val contentType: UpdateTaskContentRequest.ContentType? = null,

    @SerialName(value = "contentId") val contentId: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "transcription") val transcription: kotlin.String? = null,

    @SerialName(value = "translation") val translation: kotlin.String? = null,

    @SerialName(value = "orderNum") val orderNum: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: AUDIO,IMAGE,TEXT,VIDEO,AVATAR
     */
    @Serializable
    enum class ContentType(val value: kotlin.String) {
        @SerialName(value = "AUDIO") AUDIO("AUDIO"),
        @SerialName(value = "IMAGE") IMAGE("IMAGE"),
        @SerialName(value = "TEXT") TEXT("TEXT"),
        @SerialName(value = "VIDEO") VIDEO("VIDEO"),
        @SerialName(value = "AVATAR") AVATAR("AVATAR");
    }

}

