/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param surname 
 * @param name 
 * @param patronymic 
 * @param gender 
 * @param dob 
 * @param dor 
 * @param citizenship 
 * @param nationality 
 * @param countryOfResidence 
 * @param cityOfResidence 
 * @param countryDuringEducation 
 * @param periodSpent 
 * @param kindOfActivity 
 * @param education 
 * @param purposeOfRegister 
 */
@Serializable

data class UpdateUserProfileRequest (

    @SerialName(value = "surname") val surname: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "patronymic") val patronymic: kotlin.String? = null,

    @SerialName(value = "gender") val gender: UpdateUserProfileRequest.Gender? = null,

    @SerialName(value = "dob") val dob: kotlin.String? = null,

    @SerialName(value = "dor") val dor: kotlin.String? = null,

    @SerialName(value = "citizenship") val citizenship: kotlin.String? = null,

    @SerialName(value = "nationality") val nationality: kotlin.String? = null,

    @SerialName(value = "countryOfResidence") val countryOfResidence: kotlin.String? = null,

    @SerialName(value = "cityOfResidence") val cityOfResidence: kotlin.String? = null,

    @SerialName(value = "countryDuringEducation") val countryDuringEducation: kotlin.String? = null,

    @SerialName(value = "periodSpent") val periodSpent: UpdateUserProfileRequest.PeriodSpent? = null,

    @SerialName(value = "kindOfActivity") val kindOfActivity: kotlin.String? = null,

    @SerialName(value = "education") val education: kotlin.String? = null,

    @SerialName(value = "purposeOfRegister") val purposeOfRegister: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: MALE,FEMALE
     */
    @Serializable
    enum class Gender(val value: kotlin.String) {
        @SerialName(value = "MALE") MALE("MALE"),
        @SerialName(value = "FEMALE") FEMALE("FEMALE");
    }
    /**
     * 
     *
     * Values: MONTH_MINUS,MONTH_SIX_MONTHS_MINUS,SIX_MONTHS,YEAR_MINUS,YEAR_YEAR_PLUS,YEAR_PLUS,FIVE_YEAR_PLUS,FIVE_YEARS_PLUS,NEVER
     */
    @Serializable
    enum class PeriodSpent(val value: kotlin.String) {
        @SerialName(value = "MONTH_MINUS") MONTH_MINUS("MONTH_MINUS"),
        @SerialName(value = "MONTH_SIX_MONTHS_MINUS") MONTH_SIX_MONTHS_MINUS("MONTH_SIX_MONTHS_MINUS"),
        @SerialName(value = "SIX_MONTHS") SIX_MONTHS("SIX_MONTHS"),
        @SerialName(value = "YEAR_MINUS") YEAR_MINUS("YEAR_MINUS"),
        @SerialName(value = "YEAR_YEAR_PLUS") YEAR_YEAR_PLUS("YEAR_YEAR_PLUS"),
        @SerialName(value = "YEAR_PLUS") YEAR_PLUS("YEAR_PLUS"),
        @SerialName(value = "FIVE_YEAR_PLUS") FIVE_YEAR_PLUS("FIVE_YEAR_PLUS"),
        @SerialName(value = "FIVE_YEARS_PLUS") FIVE_YEARS_PLUS("FIVE_YEARS_PLUS"),
        @SerialName(value = "NEVER") NEVER("NEVER");
    }

}

