/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param userId 
 * @param taskId 
 * @param status 
 * @param attemptCount 
 * @param isCorrect 
 * @param lastAttemptAt 
 * @param completedAt 
 * @param shouldRetryAfterTasks 
 */
@Serializable

data class UserTaskProgressItem (

    @SerialName(value = "userId") @Required val userId: kotlin.String,

    @SerialName(value = "taskId") @Required val taskId: kotlin.String,

    @SerialName(value = "status") @Required val status: UserTaskProgressItem.Status,

    @SerialName(value = "attemptCount") @Required val attemptCount: kotlin.Int,

    @SerialName(value = "isCorrect") val isCorrect: kotlin.Boolean? = null,

    @SerialName(value = "lastAttemptAt") val lastAttemptAt: kotlin.String? = null,

    @SerialName(value = "completedAt") val completedAt: kotlin.String? = null,

    @SerialName(value = "shouldRetryAfterTasks") val shouldRetryAfterTasks: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: NOT_STARTED,IN_PROGRESS,COMPLETED,PENDING_RETRY
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "NOT_STARTED") NOT_STARTED("NOT_STARTED"),
        @SerialName(value = "IN_PROGRESS") IN_PROGRESS("IN_PROGRESS"),
        @SerialName(value = "COMPLETED") COMPLETED("COMPLETED"),
        @SerialName(value = "PENDING_RETRY") PENDING_RETRY("PENDING_RETRY");
    }

}

