/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param taskId 
 * @param themeId 
 * @param sectionId 
 * @param queuePosition 
 * @param isOriginalTask 
 * @param isRetryTask 
 * @param createdAt 
 * @param originalTaskId 
 */
@Serializable

data class UserTaskQueueItem (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "userId") @Required val userId: kotlin.String,

    @SerialName(value = "taskId") @Required val taskId: kotlin.String,

    @SerialName(value = "themeId") @Required val themeId: kotlin.String,

    @SerialName(value = "sectionId") @Required val sectionId: kotlin.String,

    @SerialName(value = "queuePosition") @Required val queuePosition: kotlin.Int,

    @SerialName(value = "isOriginalTask") @Required val isOriginalTask: kotlin.Boolean,

    @SerialName(value = "isRetryTask") @Required val isRetryTask: kotlin.Boolean,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.String,

    @SerialName(value = "originalTaskId") val originalTaskId: kotlin.String? = null

) {


}

