/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param coursesCount 
 * @param sectionsCount 
 * @param themesCount 
 * @param tasksCount 
 */
@Serializable

data class CountStats (

    @SerialName(value = "coursesCount") @Required val coursesCount: kotlin.Long,

    @SerialName(value = "sectionsCount") @Required val sectionsCount: kotlin.Long,

    @SerialName(value = "themesCount") @Required val themesCount: kotlin.Long,

    @SerialName(value = "tasksCount") @Required val tasksCount: kotlin.Long

) {


}

