/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.SectionProgressItem

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlin.time.ExperimentalTime
import kotlin.time.Instant

/**
 * 
 *
 * @param courseId 
 * @param totalTasks 
 * @param completedTasks 
 * @param progressPercentage 
 * @param sectionsProgress 
 */
@Serializable

data class CourseProgressItem @OptIn(ExperimentalTime::class) constructor(

    @Contextual val userId: String,
    @Contextual val courseId: String,
    val solvedTasks: Int,
    val totalTasks: Int,
    val percent: Double,
    val averageTimeMs: Int,
    @Contextual val updatedAt: Instant

) {


}

