/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name 
 * @param language 
 * @param isPublished 
 * @param description 
 * @param authorUrl 
 */
@Serializable

data class CreateCourseRequest (

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "language") @Required val language: kotlin.String,

    @SerialName(value = "isPublished") @Required val isPublished: kotlin.Boolean,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "authorUrl") val authorUrl: kotlin.String? = null

) {


}

