/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UserInfo

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param success 
 * @param accessToken 
 * @param refreshToken 
 * @param user 
 * @param timestamp 
 * @param message 
 */
@Serializable

data class LoginResponse (

    @SerialName(value = "success") @Required val success: kotlin.Boolean,

    @SerialName(value = "accessToken") @Required val accessToken: kotlin.String,

    @SerialName(value = "refreshToken") @Required val refreshToken: kotlin.String,

    @SerialName(value = "user") @Required val user: UserInfo,

    @SerialName(value = "timestamp") @Required val timestamp: kotlin.Long,

    @SerialName(value = "message") val message: kotlin.String? = null

) {


}

