/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param mediaId 
 * @param fileName 
 * @param mimeType 
 * @param fileSize 
 * @param fileType 
 * @param uploadedAt 
 * @param uploadedBy 
 */
@Serializable

data class MediaFileMeta (

    @SerialName(value = "mediaId") @Required val mediaId: kotlin.String,

    @SerialName(value = "fileName") @Required val fileName: kotlin.String,

    @SerialName(value = "mimeType") @Required val mimeType: kotlin.String,

    @SerialName(value = "fileSize") @Required val fileSize: kotlin.Long,

    @SerialName(value = "fileType") @Required val fileType: MediaFileMeta.FileType,

    @SerialName(value = "uploadedAt") @Required val uploadedAt: kotlin.String,

    @SerialName(value = "uploadedBy") val uploadedBy: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: IMAGE,AUDIO,VIDEO,AVATAR
     */
    @Serializable
    enum class FileType(val value: kotlin.String) {
        @SerialName(value = "IMAGE") IMAGE("IMAGE"),
        @SerialName(value = "AUDIO") AUDIO("AUDIO"),
        @SerialName(value = "VIDEO") VIDEO("VIDEO"),
        @SerialName(value = "AVATAR") AVATAR("AVATAR");
    }

}

