/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param description 
 * @param taskId 
 * @param reporterId 
 * @param createdAt 
 */
@Serializable

data class Report (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "taskId") @Required val taskId: kotlin.String,

    @SerialName(value = "reporterId") @Required val reporterId: kotlin.String,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.String

) {


}

