/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param sectionId 
 * @param totalTasks 
 * @param completedTasks 
 * @param progressPercentage 
 */
@Serializable

data class SectionProgressItem (

    @SerialName(value = "sectionId") @Required val sectionId: kotlin.String,

    @SerialName(value = "totalTasks") @Required val totalTasks: kotlin.Int,

    @SerialName(value = "completedTasks") @Required val completedTasks: kotlin.Int,

    @SerialName(value = "progressPercentage") @Required val progressPercentage: kotlin.String

) {


}

