/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlin.time.ExperimentalTime
import kotlin.time.Instant

/**
 * 
 *
 * @param sectionId 
 * @param totalTasks 
 * @param completedTasks 
 * @param progressPercentage 
 */

@Serializable
data class SectionProgressItem constructor(
    val userId: String,
    val courseId: String,
    val solvedTasks: Int,
    val totalTasks: Int,
    val percent: Double,
    val averageTimeMs: Int,
    val updatedAt: String
) {


}

