/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param userId 
 * @param name 
 * @param surname 
 * @param patronymic 
 */
@Serializable

data class StaffProfile (

    @SerialName(value = "userId") @Required val userId: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "surname") @Required val surname: kotlin.String,

    @SerialName(value = "patronymic") val patronymic: kotlin.String? = null

) {


}

