/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param email 
 * @param password 
 * @param role 
 * @param systemLanguage 
 * @param phone 
 */
@Serializable

data class StaffRegisterRequest (

    @SerialName(value = "email") @Required val email: kotlin.String,

    @SerialName(value = "password") @Required val password: kotlin.String,

    @SerialName(value = "role") @Required val role: StaffRegisterRequest.Role,

    @SerialName(value = "systemLanguage") @Required val systemLanguage: StaffRegisterRequest.SystemLanguage,

    @SerialName(value = "phone") val phone: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: STUDENT,EXPERT,CONTENT_MODERATOR,ADMIN
     */
    @Serializable
    enum class Role(val value: kotlin.String) {
        @SerialName(value = "STUDENT") STUDENT("STUDENT"),
        @SerialName(value = "EXPERT") EXPERT("EXPERT"),
        @SerialName(value = "CONTENT_MODERATOR") CONTENT_MODERATOR("CONTENT_MODERATOR"),
        @SerialName(value = "ADMIN") ADMIN("ADMIN");
    }
    /**
     * 
     *
     * Values: RUSSIAN,UZBEK,CHINESE,HINDI,TAJIK,ENGLISH
     */
    @Serializable
    enum class SystemLanguage(val value: kotlin.String) {
        @SerialName(value = "RUSSIAN") RUSSIAN("RUSSIAN"),
        @SerialName(value = "UZBEK") UZBEK("UZBEK"),
        @SerialName(value = "CHINESE") CHINESE("CHINESE"),
        @SerialName(value = "HINDI") HINDI("HINDI"),
        @SerialName(value = "TAJIK") TAJIK("TAJIK"),
        @SerialName(value = "ENGLISH") ENGLISH("ENGLISH");
    }

}

