/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.TaskAnswerItem
import org.openapitools.client.models.TaskAnswerOptionItem
import org.openapitools.client.models.TaskContentItem

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param themeId 
 * @param name 
 * @param taskType 
 * @param question 
 * @param isTraining 
 * @param orderNum 
 * @param createdAt 
 * @param content 
 * @param answerOptions 
 * @param instructions 
 * @param answer 
 */
@Serializable

data class TaskWithDetails (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "themeId") @Required val themeId: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "taskType") @Required val taskType: TaskWithDetails.TaskType,

    @SerialName(value = "question") @Required val question: kotlin.String,

    @SerialName(value = "isTraining") @Required val isTraining: kotlin.Boolean,

    @SerialName(value = "orderNum") @Required val orderNum: kotlin.Int,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.String,

    @SerialName(value = "content") @Required val content: kotlin.collections.List<TaskContentItem>,

    @SerialName(value = "answerOptions") @Required val answerOptions: kotlin.collections.List<TaskAnswerOptionItem>,

    @SerialName(value = "instructions") val instructions: kotlin.String? = null,

    @SerialName(value = "answer") val answer: TaskAnswerItem? = null

) {

    /**
     * 
     *
     * Values: LISTEN_AND_CHOOSE,READ_AND_CHOOSE,LOOK_AND_CHOOSE,MATCH_AUDIO_TEXT,MATCH_TEXT_TEXT
     */
    @Serializable
    enum class TaskType(val value: kotlin.String) {
        @SerialName(value = "LISTEN_AND_CHOOSE") LISTEN_AND_CHOOSE("LISTEN_AND_CHOOSE"),
        @SerialName(value = "READ_AND_CHOOSE") READ_AND_CHOOSE("READ_AND_CHOOSE"),
        @SerialName(value = "LOOK_AND_CHOOSE") LOOK_AND_CHOOSE("LOOK_AND_CHOOSE"),
        @SerialName(value = "MATCH_AUDIO_TEXT") MATCH_AUDIO_TEXT("MATCH_AUDIO_TEXT"),
        @SerialName(value = "MATCH_TEXT_TEXT") MATCH_TEXT_TEXT("MATCH_TEXT_TEXT");
    }

}

