/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name 
 * @param surname 
 * @param patronymic 
 * @param passwordHash 
 * @param systemLanguage 
 * @param phone 
 * @param avatarId 
 */
@Serializable

data class UpdateStaffProfileRequest (

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "surname") val surname: kotlin.String? = null,

    @SerialName(value = "patronymic") val patronymic: kotlin.String? = null,

    @SerialName(value = "passwordHash") val passwordHash: kotlin.String? = null,

    @SerialName(value = "systemLanguage") val systemLanguage: UpdateStaffProfileRequest.SystemLanguage? = null,

    @SerialName(value = "phone") val phone: kotlin.String? = null,

    @SerialName(value = "avatarId") val avatarId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: RUSSIAN,UZBEK,CHINESE,HINDI,TAJIK,ENGLISH
     */
    @Serializable
    enum class SystemLanguage(val value: kotlin.String) {
        @SerialName(value = "RUSSIAN") RUSSIAN("RUSSIAN"),
        @SerialName(value = "UZBEK") UZBEK("UZBEK"),
        @SerialName(value = "CHINESE") CHINESE("CHINESE"),
        @SerialName(value = "HINDI") HINDI("HINDI"),
        @SerialName(value = "TAJIK") TAJIK("TAJIK"),
        @SerialName(value = "ENGLISH") ENGLISH("ENGLISH");
    }

}

