/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name 
 * @param question 
 * @param instructions 
 * @param isTraining 
 * @param orderNum 
 */
@Serializable

data class UpdateTaskRequest (

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "question") val question: kotlin.String? = null,

    @SerialName(value = "instructions") val instructions: kotlin.String? = null,

    @SerialName(value = "isTraining") val isTraining: kotlin.Boolean? = null,

    @SerialName(value = "orderNum") val orderNum: kotlin.Int? = null

) {


}

