/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param status 
 * @param phone 
 * @param role 
 * @param systemLanguage 
 * @param avatarId 
 */
@Serializable

data class UpdateUserRequest (

    @SerialName(value = "status") @Required val status: UpdateUserRequest.Status,

    @SerialName(value = "phone") val phone: kotlin.String? = null,

    @SerialName(value = "role") val role: UpdateUserRequest.Role? = null,

    @SerialName(value = "systemLanguage") val systemLanguage: UpdateUserRequest.SystemLanguage? = null,

    @SerialName(value = "avatarId") val avatarId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: ACTIVE,SUSPENDED,DEACTIVATED,PENDING_VERIFICATION
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "ACTIVE") ACTIVE("ACTIVE"),
        @SerialName(value = "SUSPENDED") SUSPENDED("SUSPENDED"),
        @SerialName(value = "DEACTIVATED") DEACTIVATED("DEACTIVATED"),
        @SerialName(value = "PENDING_VERIFICATION") PENDING_VERIFICATION("PENDING_VERIFICATION");
    }
    /**
     * 
     *
     * Values: STUDENT,EXPERT,CONTENT_MODERATOR,ADMIN
     */
    @Serializable
    enum class Role(val value: kotlin.String) {
        @SerialName(value = "STUDENT") STUDENT("STUDENT"),
        @SerialName(value = "EXPERT") EXPERT("EXPERT"),
        @SerialName(value = "CONTENT_MODERATOR") CONTENT_MODERATOR("CONTENT_MODERATOR"),
        @SerialName(value = "ADMIN") ADMIN("ADMIN");
    }
    /**
     * 
     *
     * Values: RUSSIAN,UZBEK,CHINESE,HINDI,TAJIK,ENGLISH
     */
    @Serializable
    enum class SystemLanguage(val value: kotlin.String) {
        @SerialName(value = "RUSSIAN") RUSSIAN("RUSSIAN"),
        @SerialName(value = "UZBEK") UZBEK("UZBEK"),
        @SerialName(value = "CHINESE") CHINESE("CHINESE"),
        @SerialName(value = "HINDI") HINDI("HINDI"),
        @SerialName(value = "TAJIK") TAJIK("TAJIK"),
        @SerialName(value = "ENGLISH") ENGLISH("ENGLISH");
    }

}

