/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param userId 
 * @param courseId 
 * @param enrolledAt 
 * @param progress 
 * @param completedAt 
 */
@Serializable

data class UserCourseEnrollmentItem (

    @SerialName(value = "userId") @Required val userId: kotlin.String,

    @SerialName(value = "courseId") @Required val courseId: kotlin.String,

    @SerialName(value = "enrolledAt") @Required val enrolledAt: kotlin.String,

    @SerialName(value = "progress") @Required val progress: kotlin.String,

    @SerialName(value = "completedAt") val completedAt: kotlin.String? = null

) {


}

