/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UserProfile

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param success 
 * @param profile 
 * @param timestamp 
 * @param message 
 */
@Serializable

data class UserProfileResponse (

    @SerialName(value = "success") @Required val success: kotlin.Boolean,

    @SerialName(value = "profile") @Required val profile: UserProfile,

    @SerialName(value = "timestamp") @Required val timestamp: kotlin.Long,

    @SerialName(value = "message") val message: kotlin.String? = null

) {


}

