/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param language 
 * @param understands 
 * @param speaks 
 * @param reads 
 * @param writes 
 */
@Serializable

data class UserLanguageSkillRequest (

    @SerialName(value = "language") @Required val language: kotlin.String,

    @SerialName(value = "understands") @Required val understands: kotlin.Boolean,

    @SerialName(value = "speaks") @Required val speaks: kotlin.Boolean,

    @SerialName(value = "reads") @Required val reads: kotlin.Boolean,

    @SerialName(value = "writes") @Required val writes: kotlin.Boolean

) {


}

