/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.example.inrussian.components.main.profile.SystemLanguage
import kotlinx.serialization.*

/**
 * 
 *
 * @param userId 
 * @param surname 
 * @param name 
 * @param gender 
 * @param dob 
 * @param dor 
 * @param patronymic 
 * @param citizenship 
 * @param nationality 
 * @param countryOfResidence 
 * @param cityOfResidence 
 * @param countryDuringEducation 
 * @param periodSpent 
 * @param kindOfActivity 
 * @param education 
 * @param purposeOfRegister 
 */
@Serializable

data class UserProfileModel (
    val userId: String,
    val surname: String,
    val name: String,
    val patronymic: String? = null,
    val gender: Gender,
    val dob: String,
    val dor: String,
    val citizenship: String? = null,
    val nationality: String? = null,
    val countryOfResidence: String? = null,
    val cityOfResidence: String? = null,
    val countryDuringEducation: String? = null,
    val periodSpent: PeriodSpent? = null,
    val kindOfActivity: String? = null,
    val education: String? = null,
    val purposeOfRegister: String? = null,
    val avatarId: String? = null,
    val email: String,
    val systemLanguage: SystemLanguage,
    val phone: String? = null,
    val languageSkills: List<UserLanguageSkill> = emptyList()
) {

    /**
     * 
     *
     * Values: MALE,FEMALE
     */
    @Serializable
    enum class Gender(val value: kotlin.String) {
        @SerialName(value = "MALE") MALE("MALE"),
        @SerialName(value = "FEMALE") FEMALE("FEMALE");
    }
    /**
     * 
     *
     * Values: MONTH_MINUS,MONTH_SIX_MONTHS_MINUS,SIX_MONTHS,YEAR_MINUS,YEAR_YEAR_PLUS,YEAR_PLUS,FIVE_YEAR_PLUS,FIVE_YEARS_PLUS,NEVER
     */
    @Serializable
    enum class PeriodSpent(val value: kotlin.String) {
        @SerialName(value = "MONTH_MINUS") MONTH_MINUS("MONTH_MINUS"),
        @SerialName(value = "MONTH_SIX_MONTHS_MINUS") MONTH_SIX_MONTHS_MINUS("MONTH_SIX_MONTHS_MINUS"),
        @SerialName(value = "SIX_MONTHS") SIX_MONTHS("SIX_MONTHS"),
        @SerialName(value = "YEAR_MINUS") YEAR_MINUS("YEAR_MINUS"),
        @SerialName(value = "YEAR_YEAR_PLUS") YEAR_YEAR_PLUS("YEAR_YEAR_PLUS"),
        @SerialName(value = "YEAR_PLUS") YEAR_PLUS("YEAR_PLUS"),
        @SerialName(value = "FIVE_YEAR_PLUS") FIVE_YEAR_PLUS("FIVE_YEAR_PLUS"),
        @SerialName(value = "FIVE_YEARS_PLUS") FIVE_YEARS_PLUS("FIVE_YEARS_PLUS"),
        @SerialName(value = "NEVER") NEVER("NEVER");
    }
}

@Serializable
data class UserLanguageSkill(
    val userId: String,
    val language: String,
    val understands: Boolean = false,
    val speaks: Boolean = false,
    val reads: Boolean = false,
    val writes: Boolean = false
)

