/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param success 
 * @param profile 
 * @param timestamp
 * @param error
 */
@Serializable
data class UserProfileResponse (

    @SerialName(value = "success") @Required val success: kotlin.Boolean,

    @SerialName(value = "profile") val profile: UserProfileModel? = null,

    @SerialName(value = "error") val error : String? = null,

    @SerialName(value = "timestamp") @Required val timestamp: kotlin.Long,

) {


}

